/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.org.springframework.boot.spring.boot.starter.validation)
    api(libs.org.mapstruct.mapstruct)
    annotationProcessor("org.mapstruct:mapstruct-processor:1.5.5.Final")
    api(libs.org.springdoc.springdoc.openapi.starter.webmvc.ui)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    compileOnly(libs.org.projectlombok.lombok)
    annotationProcessor(libs.org.projectlombok.lombok)
    annotationProcessor("org.projectlombok:lombok-mapstruct-binding:0.2.0")
}

group = "org.labweb"
version = "0.0.1-SNAPSHOT"
description = "WebJavaLab"
java.sourceCompatibility = JavaVersion.VERSION_21

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
